CREATE TABLE IF NOT EXISTS alertSettings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  lowStockThreshold INT DEFAULT 10 NOT NULL,
  criticalStockThreshold INT DEFAULT 5 NOT NULL,
  defaultReorderQuantity INT DEFAULT 50 NOT NULL,
  emailNotificationsEnabled INT DEFAULT 0 NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
